batch_size:
  value: 256
num_epochs: 
  value: 2
num_heads:
  value: 6
num_workers: 
  value: 4
embedding_dim: 
  value: 384
depth: 
  value: 6
seq_length: 
  value: 100
lr: 
  value: 0.001
weight_decay: 
  value: 0.0001
restore_from: 
  value: 
activation:
  value: 'sigmoid'
criterion:
  value: 'BCE'
momentum:
  value: 0.9
optimizer:
  value: 'Adadelta'
dropout:
  value: 0.0
attention_type:
  value: 'default'
