batch_size:
  value: 256
num_epochs: 
  value: 100
num_heads:
  value: 1
  # default 6
num_workers: 
  value: 4
embedding_dim: 
  value: 384
depth: 
  value: 6
lr: 
  value: 0.001
weight_decay: 
  value: 0.0001
restore_from: 
  value: 
  # Leave empty to treat as None
activation:
  value: 'sigmoid'
criterion:
  value: 'BCE'
momentum:
  value: 0.9
  # Also used as beta1 of Adam and AdamW
beta2:
  value: 0.999
  # Default 0.999, used for Adam and AdamW 
optimizer:
  value: 'SGD'
  # Adadelta, Adam, AdamW, SGD
dropout:
  value: 0.0
attention_type:
  value: 'fast'
  # default, fast
